## 错误处理（三）

### Result 与 可恢复的错误 (下)

#### 传播错误

当程序中出现错误的时候，除了处理错误，还可以将错误返回给调用方，让调用方决定错误如何处理。

```
fn read_username_from_file() -> Result<String, io::Error> {
    let f = File::open("hello.txt");
    let mut f = match f {
        Ok(file) => file,
        Err(e) => return Err(e),
    };
    let mut s = String::new();
    match f.read_to_string(&&mut s) {
        Ok(_) => Ok(s),
        Err(e) => Err(e)
    }
}
```

#### ? 运算符

简化错误传播操作

* ? 运算符，传播错误的一种快捷方式
* 如：
    ```
    fn read_username_from_file() -> Result<String, io::Error> {
        // ? 表示 如果 函数表达式执行成功，则 f为ok 结果，继续执行；直接失败，则返回err结果
        let mut f = File::open("hello.txt")?;
        let mut s = String::new();
        f.read_to_string(&mut s)?;
        // 将s包裹在 OK里面返回
        Ok(s)
    }
    ```
* 如果Resut 是OK:OK 就的值就是表达式的结果，然后继续执行程序。
* 如果Result 是Err: Err 就是整个函数的返回值，就像使用了return。

#### ? 与 from 函数

* Trait std::convert::From 上的from 函数。
    * 用于错误之间的转换。
* 被?所应用的错误，会隐式的被from函数处理。
    * 他所接收的错误类型会被转化为当前函数返回类型所定义的错误类型。
* 用于：针对不同的错误原因，返回同一中错误类型。
    *  只要每个错误类型实现了转换为所返回的错误类型的from函数

#### 链式调用
```
fn read_username_from_file() -> Result<String, io::Error> {
    let mut s = String::new();
    File::open("hello.txt")?.read_to_string(&mut s)?;
    Ok(s)
}
```

#### ?运算符 只能用于返回Result的函数

如：
```
fn main() {
    let f = File::open("hello.txt")?;
    println!("Hello, world!");
}
// error[E0277]: the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `Try`)
```

#### ? 运算符与main函数

* main 函数返回类型是：()
* main 函数的返回类型也可以是：Result<T, E>
    ```
    fn main() -> Result<(), Box<dyn Error>>{
        let f = File::open("hello.txt")?;
        Ok(())
    }
    ```
* Box<dyn Error\> 是trait对象:
    * 简单理解为 “任何可能错误的错误类型”