## should_panic

使用should_panic检查恐慌

### 验证错误处理情况

* 测试除了验证代码的返回值是否正确，还需验证代码会否预期的处理了发生错误的情况
* 可验证代码在特定情况下是否发生了panic。
* should_panic属性（attribute）:
    * 函数panic，测试通过
    * 函数没有panic:测试失败。

```
pub struct Guess {
    pub value: u32,
}

impl Guess {
    pub fn new(value: u32) ->Guess {
        if value < 1 || value > 100 {
            panic!("guess value must between 1 and 100, got {}", value);
        }
        Guess{value}
    }
}
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    #[should_panic]
    fn test_new() {
        Guess::new(200);
    }
}
```

### 让should_panic更精确

* 为should_panic属性添加一个可选的expected参数：
    * 将检查失败消息中是否包含所指定的文字

```
pub struct Guess {
    pub value: u32,
}

impl Guess {
    pub fn new(value: u32) ->Guess {
        if value < 1 {
            panic!("guess value must greater than 1, got {}", value);
        } else if value > 100 {
            panic!("guess value must less than 100, got {}", value);
        }
        Guess{value}
    }
}
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    #[should_panic(expected = "guess value must less than 100")]
    fn test_new() {
        Guess::new(200);
    }
}
```

Guess::new(0); 测试失败，打印出恐慌数据及期待数据
```
base_learn11-04 git:(master) ✗ cargo test
   Compiling base_learn11-04 v0.1.0 (/Users/lucky/data/rust/study/base_learn11-04)
    Finished test [unoptimized + debuginfo] target(s) in 0.49s
     Running target/debug/deps/base_learn11_04-950ede8b46196793

running 1 test
test tests::test_new ... FAILED

failures:

---- tests::test_new stdout ----
thread 'tests::test_new' panicked at 'guess value must greater than 1, got 0', src/lib.rs:8:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
note: panic did not contain expected string
      panic message: `"guess value must greater than 1, got 0"`,
 expected substring: `"guess value must less than 100"`

failures:
    tests::test_new

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```